language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch

services:
  - mongodb

# command to install dependencies
install:
  - "pip install pytest -U" #needed for py3.3 testpass
  - "pip install -e ."

# command to run tests
script: 
  - "python setup.py test"
